export const actionTypes = {
    /*---------------------------------------------------------------------
                                HomeProcess
    -----------------------------------------------------------------------*/
    GET_AUTH_TOKEN_REQUEST: 'GET_AUTH_TOKEN_REQUEST',
    GET_AUTH_TOKEN_SUCCESS: 'GET_AUTH_TOKEN_SUCCESS',
    FETCH_SERVICES_ERROR: 'FETCH_SERVICES_ERROR',
    GET_AUFTRAG_DATA_REQUEST: 'GET_AUFTRAG_DATA_REQUEST',
    GET_AUFTRAG_DATA_SUCCESS: 'GET_AUFTRAG_DATA_SUCCESS',
    SAVE_ORDER_DETAIL_DATA_REQUEST: 'SAVE_ORDER_DETAIL_DATA_REQUEST',
    SAVE_ORDER_DETAIL_DATA_SUCCESS: 'SAVE_ORDER_DETAIL_DATA_SUCCESS',
    GET_FIRST_WEIGHT_DATA_REQUEST: 'GET_FIRST_WEIGHT_DATA_REQUEST',
    GET_FIRST_WEIGHT_DATA_SUCCESS: 'GET_FIRST_WEIGHT_DATA_SUCCESS',
    SAVE_SECOND_ORDER_DETAIL_DATA_REQUEST: 'SAVE_SECOND_ORDER_DETAIL_DATA_REQUEST',
    SAVE_SECOND_ORDER_DETAIL_DATA_SUCCESS: 'SAVE_SECOND_ORDER_DETAIL_DATA_SUCCESS',
    GET_VEHICAL_ID_REQUEST: 'GET_VEHICAL_ID_REQUEST',
    GET_VEHICAL_ID_SUCCESS: 'GET_VEHICAL_ID_SUCCESS',
    SAVE_TRANSACTION_DATA_REQUEST: 'SAVE_TRANSACTION_DATA_REQUEST',
    SAVE_TRANSACTION_DATA_SUCCESS: 'SAVE_TRANSACTION_DATA_SUCCESS',
    GET_PDF_DATA_REQUEST: 'GET_PDF_DATA_REQUEST',
    GET_PDF_DATA_SUCCESS: 'GET_PDF_DATA_SUCCESS',
    GET_VEHICAL_LIST_REQUEST: 'GET_VEHICAL_LIST_REQUEST',
    GET_VEHICAL_LIST_SUCCESS: 'GET_VEHICAL_LIST_SUCCESS',
    GET_TRANSACTION_ID_REQUEST: 'GET_TRANSACTION_ID_REQUEST',
    GET_TRANSACTION_ID_SUCCESS: 'GET_TRANSACTION_ID_SUCCESS',
    SAVE_SECOND_TRANSACTION_DATA_REQUEST: 'SAVE_SECOND_TRANSACTION_DATA_REQUEST',
    SAVE_SECOND_TRANSACTION_DATA_SUCCESS: 'SAVE_SECOND_TRANSACTION_DATA_SUCCESS',
    SAVE_PDF_DATA_TO_TRANSPORIAN_REQUEST: 'SAVE_PDF_DATA_TO_TRANSPORIAN_REQUEST',
    SAVE_PDF_DATA_TO_TRANSPORIAN_SUCCESS: 'SAVE_PDF_DATA_TO_TRANSPORIAN_SUCCESS'
}